# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://redistogo:ba753dd7ce73fdf343c07b621d35a96e@porgy.redistogo.com:9671/

development:
  adapter: async

test:
  adapter: async
